### ISSUE TITLE
Cannot reproduce paper results

### ISSUE THREAD

**Issue by PingYu-iris** [CAMTL/CA-MTL#5] opened 2021-05-06 01:38 UTC
Hi there,

Thanks for sharing the code. I am pretty excited to try the code. However, the performance cannot reproduce the paper results.

I ran the code with command:
`python run.py --model_name_or_path CA-MTL-base --data_dir $DATA_DIR --output_dir $OUTPUT_DIR --do_train --do_eval
`

The results for 
cola is 0.00286100001416597
mnli is 0.39949057564951607
rte is 0.4657039711191336
qqp is 0.6150630719762552
sst-2 is 0.6502293577981652
qnli is 0.6637378729635731

This result is a complete failure. Could you provide the command to reproduce your results in paper?

**Comment by jpilaul** [comment] 2021-05-06 13:32
Hi @PingYu-iris, thank you for taking the time to read our paper and run our code. The run command that you posted is missing quite a few arguments. For example, `--use_mt_uncertainty` is missing. We will provide the other parameters that we have used in the next few days. Layer freezing `--freeze_encoder_layers 0-N` (https://github.com/CAMTL/CA-MTL/issues/6) is also important to reach good performance.

**Comment by rimijoker** [comment] 2021-05-31 15:01
@jpilaul @Am1n3e is there any update on this?
I am trying to integrate this model into the DeepPavlov library, but I cannot reproduce the results.

**Comment by jpilaul** [comment] 2021-06-30 20:29
Thanks for your patience. I am currently on it.

**Comment by rabiulcste** [comment] 2021-07-20 03:17
```
07/19/2021 20:52:26 - INFO - transformers.trainer -   ***** Running training *****
07/19/2021 20:52:26 - INFO - transformers.trainer -     Num examples = 400
07/19/2021 20:52:26 - INFO - transformers.trainer -     Num Epochs = 3
07/19/2021 20:52:26 - INFO - transformers.trainer -     Instantaneous batch size per device = 8
07/19/2021 20:52:26 - INFO - transformers.trainer -     Total train batch size (w. parallel, distributed & accumulation) = 16
07/19/2021 20:52:26 - INFO - transformers.trainer -     Gradient Accumulation steps = 1
07/19/2021 20:52:26 - INFO - transformers.trainer -     Total optimization steps = 75
```

I am using the below command.
```
python -m torch.distributed.launch --nproc_per_node 4 run.py --model_name_or_path CA-MTL-base --data_dir glue_data --output_dir output --do_train
```

Why Num examples = 400?

**Comment by jpilaul** [comment] 2021-07-20 04:47
That's a bug that's fixed in https://github.com/CAMTL/CA-MTL/pull/8 at this line https://github.com/CAMTL/CA-MTL/pull/8/files#diff-d6af0459a37d985953d7040c14f53feb3b9cc9e58b543aa3c2b80256d276c5e0R112. PR is waiting approval.

**Comment by jpilaul** [comment] 2021-07-23 13:37
I have finished testing base and I am getting the following evaluation results for `CA-MTL-base`:
``` sql
cola = 62.6
mnli = 83.5
rte = 77.2
qqp = 90.3
qnli = 90.9
sst_2 = 92.8
mrpc = 89.7
```
Note that, except for rte, results are all higher above than in table 9 results for `8-task CA-MTL BERT-BASE`. Also note that I have stopped training at 3 epoch, whereas we trained for 5 epochs in the paper.

**Comment by rimijoker** [comment] 2021-07-25 08:23
@jpilaul thank you for providing everything to replicate the results.
I am running into this error when every I am using a single device, here is the trace:
```
StopIteration: Caught StopIteration in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/camtl/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/admin/miniconda3/envs/camtl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/admin/pal_bert/CAMTLworkspace/CA-MTL/src/model/ca_mtl.py", line 74, in forward
    task_id=task_id,
  File "/home/admin/miniconda3/envs/camtl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/admin/pal_bert/CAMTLworkspace/CA-MTL/src/model/encoders/ca_mtl_base.py", line 527, in forward
    dtype=next(self.parameters()).dtype
StopIteration 
```
Seems like it was due to two devices being visible and I was only using one, setting the env variable CUDA_VISIBLE_DEVICE resolved this.

**Closed as completed** 2021-07-27 13:20 UTC
